In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dirty_music_tours.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 20
Columns: 11

In [3]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [4]:
print("Column Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Column Names:
['Rank', 'Peak', 'All Time Peak', 'Actual\xa0gross', 'Adjusted\xa0gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)', 'Shows', 'Average gross', 'Ref.']

Data Types:
Rank                                int64
Peak                                  str
All Time Peak                         str
Actual gross                          str
Adjusted gross (in 2022 dollars)      str
Artist                                str
Tour title                            str
Year(s)                               str
Shows                               int64
Average gross                         str
Ref.                                  str
dtype: object

In [5]:
print("Missing Values Per Column:")
print(df.isnull().sum())

Missing Values Per Column:
Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [6]:
duplicate_count = df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [7]:
df.describe(include='all')

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
count,20.000000,9,6,20,20,20,20,20,20.000000,20,20
unique,NaN,7,6,20,20,9,20,16,NaN,20,20
top,NaN,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2013–2014,NaN,"$13,928,571",[1]
freq,NaN,2,1,1,1,4,1,3,NaN,1,1
mean,10.450000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.000000,NaN,NaN
std,5.942488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.507617,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.000000,NaN,NaN
25%,5.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.000000,NaN,NaN
50%,10.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.000000,NaN,NaN
75%,15.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.500000,NaN,NaN
max,20.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325.000000,NaN,NaN

In [8]:
for column in df.columns:
    print(f"\n{column}:")
    print(df[column].unique())

Rank:
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18 19 20]

Peak:
<StringArray>
['1', '1[4]', '2[7]', '2[4]', '2[10]', nan, '1[20]', '2[c]']
Length: 8, dtype: str

All Time Peak:
<StringArray>
['2', '7[2]', '2[5]', '10[7]', nan, '10[9]', '14[17]']
Length: 7, dtype: str

Actual gross:
<StringArray>
[   '$780,000,000',    '$579,800,000',    '$411,000,000',    '$397,300,000',
    '$345,675,146',    '$305,158,363',    '$280,000,000',    '$257,600,000',
    '$256,084,556',    '$250,400,000', '$229,100,000[b]',    '$227,400,000',
    '$204,000,000',    '$200,000,000',    '$194,000,000',    '$184,000,000',
    '$170,000,000',    '$169,800,000', '$167,700,000[e]',    '$150,000,000']
Length: 20, dtype: str

Adjusted gross (in 2022 dollars):
<StringArray>
['$780,000,000', '$579,800,000', '$560,622,615', '$454,751,555',
 '$402,844,849', '$388,978,496', '$381,932,682', '$257,600,000',
 '$312,258,401', '$309,141,878', '$283,202,896', '$295,301,479',
 '$251,856,802', '$299,676,265', '$281,617,035', '$227,452,347',
 '$213,568,571', '$207,046,755', '$204,486,106', '$185,423,109']
Length: 20, dtype: str

Artist:
<StringArray>
['Taylor Swift',      'Beyoncé',      'Madonna',         'Pink',
  'Celine Dion',    'Lady Gaga',   'Katy Perry',         'Cher',
        'Adele']
Length: 9, dtype: str

Tour title:
<StringArray>
[                         'The Eras Tour †',
                   'Renaissance World Tour',
              'Sticky & Sweet Tour ‡[4][a]',
              'Beautiful Trauma World Tour',
                  'Reputation Stadium Tour',
                            'The MDNA Tour',
                'Taking Chances World Tour',
                        'Summer Carnival †',
                 'The Formation World Tour',
                      'The 1989 World Tour',
          'The Mrs. Carter Show World Tour',
                  'The Monster Ball Tour *',
                     'Prismatic World Tour',
 'Living Proof: The Farewell Tour ‡[21][a]',
                         'Confessions Tour',
                'The Truth About Love Tour',
                       'Born This Way Ball',
                         'Rebel Heart Tour',
                          'Adele Live 2016',
                             'The Red Tour']
Length: 20, dtype: str

Year(s):
<StringArray>
['2023–2024',      '2023', '2008–2009', '2018–2019',      '2018',      '2012',
      '2016',      '2015', '2013–2014', '2009–2011', '2014–2015', '2002–2005',
      '2006', '2012–2013', '2015–2016', '2016–2017']
Length: 16, dtype: str

Shows:
[ 56  85 156  53  88 131  41  49 132 203 151 325  60 142  98  82 121  86]

Average gross:
<StringArray>
['$13,928,571', '$10,353,571',  '$4,835,294',  '$2,546,795',  '$6,522,173',
  '$3,467,709',  '$2,137,405',  '$6,282,927',  '$5,226,215',  '$2,945,882',
  '$1,735,606',  '$1,118,227',  '$1,350,993',    '$615,385',  '$3,233,333',
  '$1,295,775',  '$1,734,694',  '$2,070,732',  '$1,385,950',  '$1,744,186']
Length: 20, dtype: str

Ref.:
<StringArray>
[     '[1]',      '[3]',      '[6]',      '[7]',      '[8]',      '[9]',
     '[11]',     '[12]',     '[13]',     '[14]', '[15][16]',     '[18]',
     '[19]',     '[20]',      '[5]',     '[22]',      '[d]',      '[4]',
     '[25]',     '[26]']
Length: 20, dtype: str

## Data Quality Report

The initial data quality assessment was performed to identify missing values, duplicate records, incorrect data types, inconsistent formatting, and unusual values.

The dataset contains 20 rows and 11 columns. The inspection includes column data types, missing-value counts, duplicate records, descriptive statistics, and unique values.

These checks help identify the cleaning operations required before the dataset can be used for analysis.

In [9]:
before_rows = len(df)
before_duplicates = df.duplicated().sum()
before_nulls = df.isnull().sum().sum()

print("BEFORE CLEANING")
print("----------------")
print("Rows:", before_rows)
print("Duplicate rows:", before_duplicates)
print("Total missing values:", before_nulls)

BEFORE CLEANING
----------------
Rows: 20
Duplicate rows: 0
Total missing values: 25

## Missing Data Handling

The columns `Peak` and `All Time Peak` contain missing values.

Since these columns represent chart ranking information, the missing values cannot be reliably calculated from other columns. Mean or median imputation would also be inappropriate because ranking values are not continuous measurements.

Therefore, missing values in these columns are replaced with the value `Unknown`. This preserves the remaining information about the tours while clearly indicating that the ranking information was unavailable.

No rows are deleted because the dataset contains only 20 records and the other fields contain useful information.

In [10]:
df['Peak'] = df['Peak'].fillna('Unknown')
df['All Time Peak'] = df['All Time Peak'].fillna('Unknown')

print("Missing values after handling:")
print(df.isnull().sum())

Missing values after handling:
Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

In [11]:
def clean_rank(value):
    if value == 'Unknown':
        return value
    
    value = str(value)
    return value.split('[')[0]

df['Peak'] = df['Peak'].apply(clean_rank)
df['All Time Peak'] = df['All Time Peak'].apply(clean_rank)

print("Peak values:")
print(df['Peak'].unique())

print("\nAll Time Peak values:")
print(df['All Time Peak'].unique())

Peak values:
<StringArray>
['1', '2', 'Unknown']
Length: 3, dtype: str

All Time Peak values:
<StringArray>
['2', '7', '10', 'Unknown', '14']
Length: 5, dtype: str

In [12]:
money_columns = [
    'Actual\xa0gross',
    'Adjusted\xa0gross (in 2022 dollars)',
    'Average gross'
]

for column in money_columns:
    df[column] = (
        df[column]
        .astype(str)
        .str.replace(r'[$,\[\]a-zA-Z]', '', regex=True)
        .astype(float)
    )

print(df[money_columns].dtypes)

Actual gross                        float64
Adjusted gross (in 2022 dollars)    float64
Average gross                       float64
dtype: object

In [13]:
df['Tour title'] = (
    df['Tour title']
    .str.replace(r'\[[^\]]*\]', '', regex=True)
    .str.replace('†', '', regex=False)
    .str.replace('‡', '', regex=False)
    .str.replace('*', '', regex=False)
    .str.strip()
)

print(df['Tour title'].head())

0                  The Eras Tour
1         Renaissance World Tour
2            Sticky & Sweet Tour
3    Beautiful Trauma World Tour
4        Reputation Stadium Tour
Name: Tour title, dtype: str

In [14]:
df.drop(columns=['Ref.'], inplace=True)

print("Columns after removing Ref.:")
print(df.columns.tolist())

Columns after removing Ref.:
['Rank', 'Peak', 'All Time Peak', 'Actual\xa0gross', 'Adjusted\xa0gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)', 'Shows', 'Average gross']

## Standardisation

The dataset contained inconsistent formatting caused by web-scraping from Wikipedia.

Ranking columns contained citation markers such as `[4]` and `[7]`, which were removed while preserving the actual ranking values.

Monetary columns contained dollar signs, commas, and citation letters such as `[b]` and `[e]`. These non-numeric characters were removed and the values were converted to `float` for numerical analysis.

Tour titles contained Wikipedia reference symbols such as `†`, `‡`, `*`, and citation markers. These were removed to retain clean tour names.

The `Ref.` column contained only source citation references and was not required for analysis, so it was removed.

In [15]:
df['Peak'] = pd.to_numeric(df['Peak'], errors='coerce')
df['All Time Peak'] = pd.to_numeric(df['All Time Peak'], errors='coerce')

print("Ranking data types:")
print(df[['Peak', 'All Time Peak']].dtypes)

Ranking data types:
Peak             float64
All Time Peak    float64
dtype: object

In [16]:
df['Start Year'] = (
    df['Year(s)']
    .str.extract(r'(\d{4})')[0]
    .astype(int)
)

print(df[['Year(s)', 'Start Year']].head(10))

     Year(s)  Start Year
0  2023–2024        2023
1       2023        2023
2  2008–2009        2008
3  2018–2019        2018
4       2018        2018
5       2012        2012
6  2008–2009        2008
7  2023–2024        2023
8       2016        2016
9       2015        2015

In [17]:
df['Year(s)'] = (
    df['Year(s)']
    .str.replace('–', '-', regex=False)
    .str.strip()
)

print(df['Year(s)'].unique())

<StringArray>
['2023-2024',      '2023', '2008-2009', '2018-2019',      '2018',      '2012',
      '2016',      '2015', '2013-2014', '2009-2011', '2014-2015', '2002-2005',
      '2006', '2012-2013', '2015-2016', '2016-2017']
Length: 16, dtype: str

In [18]:
print("Final Data Types:")
print(df.dtypes)

Final Data Types:
Rank                                  int64
Peak                                float64
All Time Peak                       float64
Actual gross                        float64
Adjusted gross (in 2022 dollars)    float64
Artist                                  str
Tour title                              str
Year(s)                                 str
Shows                                 int64
Average gross                       float64
Start Year                            int64
dtype: object

## Data Type Correction

The dataset contained several columns stored as strings even though they represented numerical values.

The `Peak` and `All Time Peak` ranking columns were converted to numeric types. Missing ranking values are represented as `NaN` for numerical processing.

The monetary columns (`Actual gross`, `Adjusted gross`, and `Average gross`) were converted to `float` after removing currency symbols and other non-numeric characters.

The `Rank` and `Shows` columns were already stored as integers and were retained.

The `Year(s)` column was standardized by replacing the en dash with a hyphen and keeping it as a string because some tours span multiple years. A separate `Start Year` integer column was created from the first year of each tour to support numerical analysis.

In [19]:
numeric_columns = [
    'Rank',
    'Peak',
    'All Time Peak',
    'Actual\xa0gross',
    'Adjusted\xa0gross (in 2022 dollars)',
    'Shows',
    'Average gross',
    'Start Year'
]

outlier_summary = []

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
    
    outlier_summary.append({
        'Column': column,
        'Q1': Q1,
        'Q3': Q3,
        'IQR': IQR,
        'Lower Bound': lower_bound,
        'Upper Bound': upper_bound,
        'Outlier Count': len(outliers)
    })

outlier_df = pd.DataFrame(outlier_summary)

outlier_df

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count
0,Rank,5.750000e+00,1.525000e+01,9.500000e+00,-8.500000e+00,2.950000e+01,0
1,Peak,1.000000e+00,2.000000e+00,1.000000e+00,-5.000000e-01,3.500000e+00,0
2,All Time Peak,3.250000e+00,1.000000e+01,6.750000e+00,-6.875000e+00,2.012500e+01,0
3,Actual gross,1.915000e+08,3.152876e+08,1.237876e+08,5.818662e+06,5.009689e+08,2
4,Adjusted gross (in 2022 dollars),2.457557e+08,3.924451e+08,1.466894e+08,2.572159e+07,6.124792e+08,1
5,Shows,5.900000e+01,1.345000e+02,7.550000e+01,-5.425000e+01,2.477500e+02,1
6,Average gross,1.647508e+06,4.933024e+06,3.285516e+06,-3.280766e+06,9.861299e+06,2
7,Start Year,2.011250e+03,2.016500e+03,5.250000e+00,2.003375e+03,2.024375e+03,1

In [20]:
for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
    
    print(f"\n{column}: {len(outliers)} outliers")
    
    if len(outliers) > 0:
        print(outliers[[column, 'Artist', 'Tour title']].to_string(index=False))

Rank: 0 outliers

Peak: 0 outliers

All Time Peak: 0 outliers

Actual gross: 2 outliers
 Actual gross       Artist             Tour title
  780000000.0 Taylor Swift          The Eras Tour
  579800000.0      Beyoncé Renaissance World Tour

Adjusted gross (in 2022 dollars): 1 outliers
 Adjusted gross (in 2022 dollars)       Artist    Tour title
                      780000000.0 Taylor Swift The Eras Tour

Shows: 1 outliers
 Shows Artist                      Tour title
   325   Cher Living Proof: The Farewell Tour

Average gross: 2 outliers
 Average gross       Artist             Tour title
    13928571.0 Taylor Swift          The Eras Tour
    10353571.0      Beyoncé Renaissance World Tour

Start Year: 1 outliers
 Start Year Artist                      Tour title
       2002   Cher Living Proof: The Farewell Tour

## Outlier Detection and Treatment

The Interquartile Range (IQR) method was used to identify potential outliers in the numerical columns.

The analysis identified outliers in `Actual gross`, `Adjusted gross`, `Shows`, `Average gross`, and `Start Year`.

After reviewing the identified records, the outliers were found to represent genuine observations rather than data-entry errors. For example, Taylor Swift's *The Eras Tour* and Beyoncé's *Renaissance World Tour* have exceptionally high gross values because they are among the highest-grossing tours in the dataset. Similarly, Cher's *Living Proof: The Farewell Tour* has a high number of shows and an earlier start year, but these values are valid.

Therefore, no outliers were removed or capped. The identified values were retained because they provide meaningful information about the dataset.

In [21]:
# Check and remove duplicate rows

duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicate rows before cleaning:", duplicates_before)
print("Duplicate rows removed:", duplicates_before - duplicates_after)
print("Duplicate rows after cleaning:", duplicates_after)

Duplicate rows before cleaning: 0
Duplicate rows removed: 0
Duplicate rows after cleaning: 0

In [22]:
# Keep unavailable ranking values as "Unknown"
# Ranking columns are categorical/ordinal, not continuous numerical values.

df['Peak'] = df['Peak'].fillna('Unknown').astype(str)
df['All Time Peak'] = df['All Time Peak'].fillna('Unknown').astype(str)

print("Peak data type:", df['Peak'].dtype)
print("All Time Peak data type:", df['All Time Peak'].dtype)

print("\nMissing values:")
print(df.isnull().sum())

Peak data type: str
All Time Peak data type: str

Missing values:
Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Start Year                          0
dtype: int64

In [23]:
# Calculate final cleaning statistics

after_rows = len(df)
after_duplicates = df.duplicated().sum()
after_nulls = df.isnull().sum().sum()

# Create Before vs After summary
before_after_summary = pd.DataFrame({
    'Metric': [
        'Null Count',
        'Duplicate Count',
        'Row Count',
        'Dtype Accuracy'
    ],
    'Before Cleaning': [
        before_nulls,
        before_duplicates,
        before_rows,
        'Needs correction'
    ],
    'After Cleaning': [
        after_nulls,
        after_duplicates,
        after_rows,
        'Correct'
    ]
})

before_after_summary

            Metric   Before Cleaning After Cleaning
0       Null Count                25              0
1  Duplicate Count                 0              0
2        Row Count                20             20
3   Dtype Accuracy  Needs correction        Correct

## Before vs After Cleaning Summary

The comparison shows the improvement achieved through the data cleaning process.

- Missing values were reduced from 25 to 0 by handling unavailable ranking information.
- No duplicate records were found, so no rows were removed due to duplication.
- The dataset retained all 20 original records.
- Data types were corrected for numerical, monetary, ranking, and year-related fields.
- Inconsistent formatting, currency symbols, citation markers, and unnecessary reference information were cleaned.

In [24]:
# Final inspection of the cleaned dataset

print("Final Dataset Shape:", df.shape)

print("\nFinal Data Types:")
print(df.dtypes)

print("\nFinal Missing Values:")
print(df.isnull().sum())

print("\nFinal Duplicate Rows:", df.duplicated().sum())

print("\nFirst 5 Rows of Cleaned Dataset:")
display(df.head())

Final Dataset Shape: (20, 11)

Final Data Types:
Rank                                  int64
Peak                                    str
All Time Peak                           str
Actual gross                        float64
Adjusted gross (in 2022 dollars)    float64
Artist                                  str
Tour title                              str
Year(s)                                 str
Shows                                 int64
Average gross                       float64
Start Year                            int64
dtype: object

Final Missing Values:
Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Start Year                          0
dtype: int64

Final Duplicate Rows: 0

First 5 Rows of Cleaned Dataset:

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Start Year
0,1,1.0,2.0,780000000.0,780000000.0,Taylor Swift,The Eras Tour,2023-2024,56,13928571.0,2023
1,2,1.0,7.0,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,2023,56,10353571.0,2023
2,3,1.0,2.0,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,2008-2009,85,4835294.0,2008
3,4,2.0,10.0,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,2018-2019,156,2546795.0,2018
4,5,2.0,Unknown,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,2018,53,6522173.0,2018

In [25]:
# Final formatting for ranking columns

df['Peak'] = df['Peak'].apply(
    lambda x: 'Unknown' if x == 'Unknown' else str(int(float(x)))
)

df['All Time Peak'] = df['All Time Peak'].apply(
    lambda x: 'Unknown' if x == 'Unknown' else str(int(float(x)))
)

print(df[['Peak', 'All Time Peak']].head())

print("\nMissing values:")
print(df.isnull().sum().sum())

  Peak All Time Peak
0    1             2
1    1             7
2    1             2
3    2            10
4    2       Unknown

Missing values:
0

In [26]:
# Save the cleaned dataset

df.to_csv("cleaned_music_tours.csv", index=False)

print("Cleaned dataset saved successfully!")
print("File: cleaned_music_tours.csv")

Cleaned dataset saved successfully!
File: cleaned_music_tours.csv

## Final Cleaning Summary

The dataset was systematically cleaned and transformed into an analysis-ready format.

### Cleaning Operations Performed

1. **Missing Values**
   - Missing values in `Peak` and `All Time Peak` were identified.
   - Since these ranking values could not be reliably inferred, unavailable values were represented as `Unknown`.
   - No rows were deleted.

2. **Duplicate Records**
   - Duplicate rows were checked.
   - No duplicate records were found.
   - Therefore, 0 rows were removed.

3. **Standardisation**
   - Citation markers and unwanted symbols were removed from ranking values and tour titles.
   - Currency symbols, commas, and citation characters were removed from monetary columns.
   - The `Year(s)` column was standardized by replacing en dashes with hyphens.

4. **Data Type Correction**
   - Monetary columns were converted to floating-point numbers.
   - `Rank` and `Shows` were retained as integers.
   - Ranking columns were kept as strings so that unavailable values could be represented as `Unknown`.
   - A numeric `Start Year` column was created from the first year of each tour.

5. **Outlier Detection**
   - The IQR method was used to identify potential outliers.
   - Several high values were detected in gross, shows, and start-year columns.
   - These values were reviewed and found to represent genuine observations rather than errors.
   - Therefore, no outliers were removed or capped.

6. **Unnecessary Columns**
   - The `Ref.` column was removed because it contained source citation information that was not required for analysis.

### Final Result

The cleaned dataset contains **20 rows and 10 columns** and is ready for further analysis.

The cleaned data was saved as:

`cleaned_music_tours.csv`